apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pxc-operator
  namespace: pxc
spec:
  interval: 30m
  chart:
    spec:
      chart: pxc-operator
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: pxc
      interval: 12h
