apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password-sdk
spec:
  provider:
    onepasswordSDK:
      vault: homelab
      auth:
        serviceAccountSecretRef:
          namespace: external-secrets
          name: 1password-token
          key: token
