apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  target:
    name: client-info-secret
    creationPolicy: Owner
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: storage-admin/client-info.yml
