apiVersion: v1
kind: Service
metadata:
  name: pulse
  namespace: ghost
  labels:
    app.kubernetes.io/name: pulse
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: pulse
