apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost
  namespace: ghost
  labels:
    app.kubernetes.io/name: ghost
data:
  config.development.json: |
    {
      "url": "http://ghost.localhost/",
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "sqlite3",
        "connection": {
          "filename": "/home/nonroot/app/ghost/content/data/ghost.db"
        }
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": [
          "stdout"
        ]
      },
      "process": "local",
      "paths": {
        "contentPath": "/home/nonroot/app/ghost/content"
      }
    }
