apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost
  namespace: ghost
  labels:
    app.kubernetes.io/name: ghost
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ghost-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.production.json: |
          {
            "url": "http://dev.neokube.net/",
            "admin": {
              "url": "http://dev.neokube.net/"
            },
            "server": {
              "port": 2368,
              "host": "0.0.0.0"
            },
            "database": {
              "client": "mysql",
              "connection": 
              {
                "host": "pxc-db-haproxy.pxc.svc.cluster.local",
                "user": "ghost",
                "password": "{{ .password }}",
                "database": "ghost",
                "port": "3306"
              }
            },
            "mail": {
              "transport": "Direct"
            },
            "logging": {
              "transports": [
                "stdout"
              ]
            },
            "process": "local",
            "paths": {
              "contentPath": "/home/nonroot/app/ghost/content"
            }
          }
  data:
    - secretKey: password
      remoteRef:
        key: secrets/ghost
        property: password
