apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-csi
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.11.0"
      sourceRef:
        kind: HelmRepository
        name: nfs-csi
        namespace: kube-system
      interval: 12h
