---
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - TFTPD_OPTS='--tftp-single-port'
    volumes:
      - ./config:/config
      - ./assets:/assets
    ports:
      - "3000:3000"
      - "69:69/udp"
      - "8080:80"
    restart: unless-stopped
