apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: homepage-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        kubernetes.yaml: |
          mode: cluster
          gateway: true
        settings.yaml: |
          background: http://192.168.1.4:8080/deathstranding.png
        custom.css: ""
        custom.js: ""
        bookmarks.yaml: ""
        services.yaml: |
          - Widgets:
            - Minecraft:
                icon: minecraft
                widget:
                    type: gamedig
                    serverType: minecraftbe
                    url: udp://192.168.1.33:19132
                    fields: ["name", "players", "ping"]
            - Pi-hole:
                  href: http://192.168.1.11:80/admin
                  icon: pi-hole.png
                  widget:
                    type: pihole
                    url: http://192.168.1.11:80
                    version: 6
                    key: {{ .piholekey }}
            - Proxmox:
                  href: https://lud.neokube.net 
                  icon: proxmox.png
                  widget:
                    type: proxmox
                    url: https://lud.neokube.net
                    username: {{ .proxmoxusername }}
                    password: {{ .proxmoxpassword }}
                    node: lud 
            - Synology:
                  href: https://darktower.neokube.net
                  icon: synology.png
                  widget:
                    type: diskstation
                    url: https://darktower.neokube.net
                    username: {{ .synologyusername }}
                    password: {{ .synologypassword }}
                    volume: volume1
        widgets.yaml: |
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
          - resources:
              backend: resources
              expanded: true
              cpu: true
              memory: true
              network: default
          - search:
              provider: duckduckgo
              target: _blank
        docker.yaml: ""
  data:
    - secretKey: piholekey
      remoteRef:
        key: secrets/pihole
        property: piholekey
    - secretKey: synologyusername
      remoteRef:
        key: secrets/synology
        property: username
    - secretKey: synologypassword
      remoteRef:
        key: secrets/synology
        property: password
    - secretKey: proxmoxusername
      remoteRef:
        key: secrets/proxmox
        property: username
    - secretKey: proxmoxpassword
      remoteRef:
        key: secrets/proxmox
        property: password
